#!/bin/sh

touch /etc/swift/container-server/1.conf

printf "
[DEFAULT]
devices = /srv/1/node
mount_check = false
bind_port = 6011
user = swift
log_facility = LOG_LOCAL2

[pipeline:main]
pipeline = container-server

[app:container-server]
use = egg:swift#container

[container-replicator]
vm_test_mode = yes

[account-updater]

[account-auditor]

[container-sync]
" > /etc/swift/container-server/1.conf

sed -e "s/srv\/1/srv\/2/" -e "s/601/602/" -e "s/LOG_LOCAL2/LOG_LOCAL3/" /etc/swift/container-server/1.conf | sudo tee -a /etc/swift/container-server/2.conf >> log/sed.log
sed -e "s/srv\/1/srv\/3/" -e "s/601/603/" -e "s/LOG_LOCAL2/LOG_LOCAL4/" /etc/swift/container-server/1.conf | sudo tee -a /etc/swift/container-server/3.conf >> log/sed.log
sed -e "s/srv\/1/srv\/4/" -e "s/601/604/" -e "s/LOG_LOCAL2/LOG_LOCAL5/" /etc/swift/container-server/1.conf | sudo tee -a /etc/swift/container-server/4.conf >> log/sed.log


