# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the #{PG_PASS} driver:
#   gem install #{PG_PASS}
# On Mac OS X with macports:
#   gem install #{PG_PASS} -- --with-#{PG_PASS}-config=/opt/local/lib/postgresql84/bin/#{PG_PASS}_config
# On Windows:
#   gem install #{PG_PASS}
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem '#{PG_PASS}'
#
development:
  adapter: postgresql
  encoding: utf8
  database: cloud_development
  host: localhost
  pool: 5
  username: postgres
  password: pg

nova_development:
  adapter: mysql
  encoding: utf8
  database: nova
  username: root
  password: root
  host: localhost

glance_development:
  adapter: mysql
  encoding: utf8
  database: glance
  username: root
  password: root
  host: localhost


  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  encoding: utf8
  database: cloud_test
  host: localhost
  pool: 5
  username: postgres
  password: pg

nova_test:
  adapter: mysql
  encoding: utf8
  database: nova
  username: root
  password: root
  host: localhost

glance_test:
  adapter: mysql
  encoding: utf8
  database: glance
  username: root
  password: root
  host: localhost


production:
  adapter: postgresql
  encoding: utf8
  database: cloud_production
  host: localhost
  pool: 5
  username: postgres
  password: pg

nova_production:
  adapter: mysql
  encoding: utf8
  database: nova
  username: root
  password: Kikrat
  host: localhost

glance_production:
  adapter: mysql
  encoding: utf8
  database: glance
  username: root
  password: Kikrat
  host: localhost


