#!/bin/sh

if [ $# -ne 1 ] ; then 
    printf "Usage: nova-boot NAME FLAVOR KEY\n"
    exit 1 
fi

NAME=$1
FLAVOR=${2:-2}
KEY=${3:-ssh/openstack}

IMAGE_ID=$(nova image-list | awk "/${IMAGE_NAME}/ { print \$2 }")

nova boot $NAME --image $IMAGE_ID --flavor $FLAVOR --key_name \ssh\keys\$KEY
