#!/bin/sh

IP=$1

printf "
--dhcpbridge_flagfile=/etc/nova/nova.conf
--dhcpbridge=/usr/bin/nova-dhcpbridge
--logdir=/var/log/nova
--state_path=/var/lib/nova
--lock_path=/var/lock/nova
--force_dhcp_release
--iscsi_helper=tgtadm
--libvirt_use_virtio_for_bridges=true
--connection_type=libvirt
--root_helper=sudo nova-rootwrap
--ec2_private_dns_show_ip
--sql_connection=mysql://nova:openstack@$IP/nova
--use_deprecated_auth
--s3_host=$IP
--rabbit_host=$IP
--ec2_host=$IP
--ec2_dmz_host=$IP
--public_interface=eth1
--image_service=nova.image.glance.GlanceImageService
--glance_api_servers=$IP:9292
--auto_assign_floating_ip=true
--scheduler_default_filters=AllHostsFilte
--routing_source=$IP
--my_ip=$IP" >> /etc/nova/nova.conf
